export enum AnalyticsEvents {
  REDO_CREATED = "REDO_CREATED",
  REDO_POSTPONED = "REDO_POSTPONED",
  REDO_PAUSED = "REDO_PAUSED",
  REDO_DELETED = "REDO_DELETED",
  PORTFOLIO_VISITED = "PORTFOLIO_VISITED",
}
